name: PlatformIO CI

on:
  push:
  schedule:
    - cron:  '0 0 * * *'  # Every midnight.

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Build
      run: pio run -e nano328 -e feather328 -e featherm0
    - name: Test
      run: pio test -e native
