name: PlatformIO CI

on:
  push:
  schedule:
    - cron:  '0 0 * * *'  # Every midnight.

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Build
      run: pio run -e nanoatmega328
    - name: Test
      run: pio test -e native
